UBL21\Common\CommonAggregateComponents\EnvironmentalEmission:
    xml_root_name: EnvironmentalEmission
    xml_root_namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
